image: alpine
  
upload_egg:
  script:
    # add git as part of the egg upload
    - apk update && apk add git
    - git config --global user.email "null@null.com"
    - git config --global user.name "null"

    # Check if the package is actually installable
    - apk add python
    - apk add --no-cache --virtual .build-deps gcc musl-dev
    - apk add python-dev
    - apk add libffi-dev openssl-dev
    - apk add py-pip
    - pip install -U devpi-web devpi-client

    # make sure there's only 1 "__version__=" line in the setup.py file
    - (if [ "$(sed -n "/.*\(__version__\).*=.*\'.*/p" boto/__init__.py | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/' | wc -l)" == "1" ]; then echo "Found the version number"; else echo "Fail"; exit 33; fi);
    # update version to put custom ContextLogic version
    - version_origin=$(sed -n "/.*\(__version__\).*=.*\'.*/p" boto/__init__.py | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/')
    - version_cl="$version_origin+cl$CI_PIPELINE_ID"
    - sed -i "s/$version_origin/$version_cl/g" boto/__init__.py
    - pip install .
    - pip show $CI_PROJECT_NAME

  #   # Upload to Wish Pypi
  #   - devpi use $PYPI_SERVER
  #   - devpi login $USERNAME --password=$PASSWORD
  #   - devpi use $INDEX
  #   - devpi upload
  # only:
  #   - master
